
import Footer from "@/components/Footer";
import "../globals.css";
import Navigation from "@/components/Navigation";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pt-16">
        <Navigation />
        {children} 
        <Footer/>
      </body>
    </html>
  );
}
